// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTAclCommon = "t_acl_common"

// TAclCommon 權限共用表
type TAclCommon struct {
	AclCommonID    int64  `gorm:"column:AclCommonId;primaryKey;autoIncrement:true;comment:ACL COMMON ID" json:"AclCommonId"` // ACL COMMON ID
	ParentCommonID int64  `gorm:"column:ParentCommonId;comment:父ACL COMMON ID" json:"ParentCommonId"`                        // 父ACL COMMON ID
	Key            string `gorm:"column:Key;comment:ACL碼" json:"Key"`                                                        // ACL碼
	Name           string `gorm:"column:Name;comment:ACL名稱" json:"Name"`                                                     // ACL名稱
	API            string `gorm:"column:Api;comment:API Uri" json:"Api"`                                                     // API Uri
	IsLog          bool   `gorm:"column:IsLog;not null;comment:是否寫log,0-不寫入,1-寫入" json:"IsLog"`                              // 是否寫log,0-不寫入,1-寫入
}

// TableName TAclCommon's table name
func (*TAclCommon) TableName() string {
	return TableNameTAclCommon
}
