// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTAclRoleMap = "t_acl_role_map"

// TAclRoleMap Acl和Role關聯表
type TAclRoleMap struct {
	ID     int64 `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	RoleID int64 `gorm:"column:RoleId;comment:角色ID" json:"RoleId"` // 角色ID
	AclID  int64 `gorm:"column:AclId;comment:ACL ID" json:"AclId"` // ACL ID
	UserID int64 `gorm:"column:UserId" json:"UserId"`
}

// TableName TAclRoleMap's table name
func (*TAclRoleMap) TableName() string {
	return TableNameTAclRoleMap
}
