// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTRole = "t_role"

// TRole 角色列表
type TRole struct {
	RoleID     int64     `gorm:"column:RoleId;primaryKey;autoIncrement:true;comment:角色ID" json:"RoleId"` // 角色ID
	RoleName   string    `gorm:"column:RoleName;comment:角色名稱" json:"RoleName"`                           // 角色名稱
	Memo       string    `gorm:"column:Memo;comment:備註" json:"Memo"`                                     // 備註
	Status     int32     `gorm:"column:Status;not null;comment:状态,1-启用,0-禁用" json:"Status"`              // 状态,1-启用,0-禁用
	Level      int32     `gorm:"column:Level;not null;comment:等級" json:"Level"`                          // 等級
	Creator    string    `gorm:"column:Creator;comment:創建人" json:"Creator"`                              // 創建人
	Updater    string    `gorm:"column:Updater;comment:修改人" json:"Updater"`                              // 修改人
	UpdateTime time.Time `gorm:"column:UpdateTime;comment:修改時間" json:"UpdateTime"`                       // 修改時間
	CreateTime time.Time `gorm:"column:CreateTime;comment:創建時間" json:"CreateTime"`                       // 創建時間
	MerchantID string    `gorm:"column:MerchantId" json:"MerchantId"`
	FullPath   string    `gorm:"column:FullPath" json:"FullPath"`
}

// TableName TRole's table name
func (*TRole) TableName() string {
	return TableNameTRole
}
