version: '3.8'
services:
  go-admin-api:
    container_name: my-webserver
    image: my-webserver:latest
    privileged: true
    restart: always
    ports:
      - 8081:8081
    networks:
      - myweb
networks:
  myweb:
    driver: bridge
