apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-job
              image: my-cron:1.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
