apiVersion: v1
kind: Service
metadata:
  name: nginx-rpgserver
  namespace: default
spec:
  selector:
    app: go-rpcserver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
