apiVersion: v1
kind: Service
metadata:
  name: nginx-rpgserver2
  namespace: default
spec:
  selector:
    app: go-rpcserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
