apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-practice-deployment
  labels:
    app: go-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-practice
  template:
    metadata:
      labels:
        app: go-practice
    spec:
      containers:
      - name: go-practice
        image: go-practice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: go-practice-storage
          mountPath: /data
    
      volumes:
      - name: go-practice-storage
        persistentVolumeClaim:
          claimName: my-pvc  # PVC 名稱
