server:
  port: 8081
  host: "localhost"
  namespace: "bbbb"
  secretkey: "secretkey"
  refeshkey: "refreskkey"
redis:
  port: 6379
  host: "127.0.0.1"
  password: ""
  db: 1

grpc:
  host: "192.168.105.44"
  port: 80

mysql:
  port: 3306
  host: "192.168.1.171"
  username: "root"
  password: "1qaz@WSX"
  db: "gormtest"

mysqls:
  - name: mysql1
    port: 3306
    host: "192.168.1.171"
    username: "root"
    password: "1qaz@WSX"
    db: "gormtest"
  - name: mysql2
      port: 3306
      host: "192.168.1.172"
      username: "root"
      password: "1qaz@WSX"
      db: "gormtest"
